FROM golang:1.19

ENV MYSQL_HOST=host \
    MYSQL_USER=user \
    MYSQL_PORT=port \
    MYSQL_PASSWORD=password \
    MYSQL_DBNAME=dbname 
    

WORKDIR /app


COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go mod tidy


RUN go build -o todo .

# CMD /docker-gs-ping -MYSQL_HOST=$MYSQL_HOST -MYSQL_USER=$MYSQL_USER -MYSQL_PORT=$MYSQL_PORT -MYSQL_PASSWORD=$MYSQL_PASSWORD -MYSQL_DBNAME=$MYSQL_DBNAME

# CMD ["./todo","-MYSQL_HOST=$MYSQL_HOST","-MYSQL_USER=${MYSQL_USER}","-MYSQL_PORT=${MYSQL_PORT}","-MYSQL_DBNAME=${MYSQL_DBNAME}","-MYSQL_PASSWORD=${MYSQL_PASSWORD}"]
CMD ./todo -MYSQL_HOST=$MYSQL_HOST -MYSQL_USER=$MYSQL_USER -MYSQL_PORT=$MYSQL_PORT -MYSQL_DBNAME=$MYSQL_DBNAME -MYSQL_PASSWORD=$MYSQL_PASSWORD

# docker run --name todo -e MYSQL_HOST=host -e MYSQL_USER=user -e MYSQL_PORT=port -e MYSQL_PASSWORD=pw -e MYSQL_DBNAME=name -p 8090:3003 to-do-app:1.1